### ISSUE TITLE
extension of model

### ISSUE THREAD

**Issue by pinkfloydisch** [baladutt/modeling-epidemics-COVID-19#2]
Hi

Thanks for your nice and very useful code.
May I ask you to help me to extend this code to SEIRD model? D is the number of dead peoples and and 'mu': death rate, for example, mu is the rate which will be added as : (mu*I) to dI/dt

I don't know in this case, how to estimate the additional parameter "mu". I am a mathematician and not good enough in coding, but I found your current results very interesting.
Thanks
Nik

**Comment by charugarg93** [comment]
Good to know, Nik !  We will try implementing it and then get back to you.

**Comment by pinkfloydisch** [comment]
Thanks alot
